FROM {{ image_spec("cinder-base") }}
MAINTAINER {{ maintainer }}

COPY cinder_sudoers /etc/sudoers.d/cinder_sudoers

RUN chmod 750 /etc/sudoers.d \
    && chmod 440 /etc/sudoers.d/cinder_sudoers

USER cinder
