FROM {{ image_spec("cinder-base") }}
MAINTAINER {{ maintainer }}

RUN apt-get update \
    && apt-get install -y --no-install-recommends qemu-utils \
           ceph-common \
           python-ceph \
           python-rados \
    && apt-get clean \
    && mkdir -p /etc/ceph \
    && chown -R cinder: /etc/ceph \
    && ln -s /usr/lib/python2.7/dist-packages/rados.so /var/lib/microservices/venv/local/lib/python2.7/site-packages/rados.so \
    && ln -s /usr/lib/python2.7/dist-packages/rados-0.egg-info /var/lib/microservices/venv/local/lib/python2.7/site-packages/rados-0.egg-info \
    && ln -s /usr/lib/python2.7/dist-packages/rbd-0.egg-info /var/lib/microservices/venv/local/lib/python2.7/site-packages/rbd-0.egg-info \
    && ln -s /usr/lib/python2.7/dist-packages/rbd.so /var/lib/microservices/venv/local/lib/python2.7/site-packages/rbd.so

USER cinder
